name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

permissions:
  contents: write  # allow pushing to gh-pages

jobs:
  jekyll-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # use a version compatible with your setup
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build the site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
